core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views


# recipes:recipe
app_name = 'recipes'

urlpatterns = [
    path('', views.home, name="home"),
    path('recipes/category/<int:category_id>/', views.category, name="category"),
    path('recipes/<int:id>/', views.recipe, name="recipe"),
]

home/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to="recipes/covers/%Y/%m/%d/", blank=True, default='')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

home/views.py
from django.shortcuts import render
from utils.recipes.factory import make_recipe
from home.models import Recipe

def home(request):
    recipes = Recipe.objects.filter(
        is_published=True
    ).order_by('-id')
    return render(request, 'home/pages/home.html', context = {
        'recipes': recipes,
    })

def category(request, category_id):
    recipes = Recipe.objects.filter(
        category__id=2,
        is_published=True
        ).order_by('-id')
    
    category_name = (
        getattr(recipes.first(), 'category', None),
        'name',
        'Not found'
    )

    return render(request, 'home/pages/category.html', context = {
        'recipes': recipes,
        'title': f'{category_name}'
    })

def recipe(request, id):
    return render(request, 'home/pages/recipe-view.html', context = {
        'recipe': make_recipe(),
        'is_detail_page': True,
    })

home/templates/home/pages/category.html
{% extends 'global/base.html' %}

{% block title%}{{ title }} - Category | {% endblock title%}

{% block content %}
  <div class="main-content main-content-list container">
    {% for recipe in recipes %}
      {% include 'home/partials/recipe.html' %}
    {% endfor %}
  </div>
{% endblock content %}

home/templates/home/pages/home.html
{% extends 'global/base.html' %}

{% block title%}HOME | {% endblock title%}

{% block content %}
  <div class="main-content main-content-list container">
    {% for recipe in recipes %}
      {% include 'home/partials/recipe.html' %}
    {% endfor %}
  </div>
{% endblock content %}

home/templates/home/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title%}ALTERAR | {% endblock title%}

{% block content %}
  <div class="main-content main-content-detail container">
    {% include 'home/partials/recipe.html' %}
  </div>
{% endblock content %}

home/templates/home/partials/footer.html
<footer class="main-footer">
    <div class="developer">
          <a href="" target="_blank" rel="no referrer noopener">Jefferson Guedes</a>
    </div>
    <div class="powered">
          <a href="" target="_blank" rel="no referrer noopener">Powered by Django</a>
    </div>     
</footer>

home/templates/home/partials/head.html
{% load static %}

<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/brands.min.css" integrity="sha512-EJp8vMVhYl7tBFE2rgNGb//drnr1+6XKMvTyamMS34YwOEFohhWkGq13tPWnK0FbjSS6D8YoA3n3bZmb3KiUYA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/fontawesome.min.css" integrity="sha512-B46MVOJpI6RBsdcU307elYeStF2JKT87SsHZfRSkjVi4/iZ3912zXi45X5/CBr/GbCyLx6M1GQtTKYRd52Jxgw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/solid.min.css" integrity="sha512-/r+0SvLvMMSIf41xiuy19aNkXxI+3zb/BN8K9lnDDWI09VM0dwgTMzK7Qi5vv5macJ3VH4XZXr60ip7v13QnmQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="{% static 'home/css/style.css' %}" />
<link rel="stylesheet" href="{% static 'global/css/global_style.css' %}" />

home/templates/home/partials/header.html
<header class="main-header-container">
  <div class="main-header container">
    <h1>
      <a class="main-logo" href="{% url 'recipes:home' %}">
        <i class="fas fa-utensils main-logo-icon"></i>
        <span class="main-logo-text">Receitas</span>
      </a>
    </h1>
  </div>
</header>

home/templates/home/partials/recipe.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %}
      <div class="recipe recipe-cover">
        <a href="{% url 'recipes:recipe' recipe.id %}">
          <img src="{{ recipe.cover.url }}" alt="Temporário" />
        </a>
      </div>
    {% endif %}
    <div class="recipe-title-container">
      <h2 class="recipe-title">
        <a href="{% url 'recipes:recipe' recipe.id %}">
         {{ recipe.title }}
        </a>
      </h2>
    </div>
    <div class="recipe-author">
        <span class="recipe-author-item">
          <i class="fas fa-user"></i>
          {% if recipe.author is not None %}
            {% if recipe.author.first_name %}
              {{ recipe.author.first_name }} {{ recipe.author.last_name }}
            {% else %}
              {{ recipe.author.username }}
            {% endif %}
          {% else %}
            Desconhecido
          {% endif %}
        </span>
      <span class="recipe-author-item">
        <i class="fas fa-calendar-alt"></i>
        {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}
      </span>
      {% if recipe.category is not None %}
        <span class="recipe-author-item">
          <a href="{% url 'recipes:category' recipe.category.id %}">
            <i class="fas fa-layer-group"></i>
            <span>{{ recipe.category.name }}</span>
          </a>
        </span>
      {% endif %}
    </div>
    <div class="recipe-content">
      <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
      <div class="recipe-meta recipe-preparation">
        <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
        <div class="recipe-meta-text">{{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}</div>
      </div>
      <div class="recipe-meta recipe-servings">
        <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Preparo</h3>
        <div class="recipe-meta-text">{{ recipe.servings }} {{ recipe.servings_unit }}</div>
      </div>
    </div>

    {% if is_detail_page is not True %}
      <footer class="recipe-footer">
        <a href="{% url 'recipes:recipe' recipe.id %}" class="recipe-read-more button button-dark button-full-width">
          <i class="fas fa-eye"></i>
          <span>ver mais...</span>
        </a>
      </footer>
    {% endif %}

    {% if is_detail_page is True %}
      <div class="preparation-steps">
        {{ recipe.preparation_steps|linebreaksbr }}
      </div>
    {% endif %}
</div>

home/templates/home/partials/search.html
<div class="search-container">
  <div class="container">
    <form action="" class="search-form">
      <input type="search" class="search-input" name="search" />
      <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
    </form>
  </div>
</div>